name: GitHub Actions On Push
run-name: ${{ github.actor }} is running shellcheck action 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
